### ISSUE TITLE
Raspberry Pi 3 - Web page up - Still Not pairing

### ISSUE THREAD

**Issue by DrIanGregory** [VRGhost/PyPush#15]
- With Raspberry Pi 3. Got the webpage up using the steps in issue ([SOLUTIONS] For your troubleshooting!! #14).
 
- Running this command as root:

`./bin/serve.sh --ble_driver pybluez --ble_device hci0  web_ui`

- Then waiting for the  Microbot to pair. Every time I run it. I receive any of the following errors. Any ideas?
NOTE: If I run the command:
`sudo hcitool lescan`
The device "D4:A7:0A:F4:31:CC mib-push". Is the first in the list.

- But I see this display message:
2017-07-06 23:39:04,385 daemon    line:117  INFO     Microbot u'D4:A7:0A:F4:31:CC' not found

- ERROR 1: After several scanning iterations then, terminates the program with this.

(process:11544): GLib-CRITICAL **: g_io_channel_read_chars: assertion 'channel->is_readable' failed

- ERROR 2: After several scanning iterations then, terminates the program with this.

Bus error

- ERROR 3: After several scanning iterations then, terminates the program with this.
*** Error in `python': double free or corruption (fasttop): 0x75101710 ***
Aborted

- ERROR 4: This is from the Webpage log.
File "PyPush/core/ble/daemon.py", line 60, in step
    actionResult = self._callAction(uuid, cmd, args, kwargs)
  File "PyPush/core/ble/daemon.py", line 130, in _callAction
    for colour in mb.pair():
  File "PyPush/lib/microbot/microbot.py", line 152, in pair
    conn = self._bleApi.connect(self._bleMb)
  File "PyPush/lib/ble/bluez/api.py", line 38, in connect
    conn._open()
  File "PyPush/lib/ble/bluez/connection.py", line 100, in _open
    self._populateCaches()
  File "PyPush/lib/ble/bluez/connection.py", line 194, in _populateCaches
    for service in conn.discover_primary():
  File "PyPush/lib/ble/bluez/connection.py", line 67, in _wrapper_
    raise exceptions.BleException(err.message)
BleException: Characteristic value/descriptor operation failed: Internal application error: I/O

**Comment by javaftper** [comment]
In your previous issue (#14) you mentioned editing the swap configuration.

To me your error looks memory related (polling a non-readable file) and swap files on SD cards are not reliable.

I overcame the memory issue with zram- compressed RAM algorithm (https://www.youtube.com/watch?v=IBNZLREqBxg).

Can you undo your swap file change and try zram?
