### ISSUE TITLE
Add push lib documentation.

### ISSUE THREAD

**Issue by VRGhost** [VRGhost/PyPush#5]

**Comment by CynthiaStar** [comment]
The link "Microbot Push Library Documentation" just says "hello world"...
Also, would be nice to know other things like why use "Bluegiga BLED112" and not the onboard Raspberry Pi 3's Bluetooth or any other bluetooth dongle.
This is a great project, but a bit of effort and guess work out of the box. (which doesn't need to be).

**Comment by VRGhost** [comment]
Feel free to contribute though.
