### ISSUE TITLE
 Help, how to install PyPush on a Raspberry Pi 3

### ISSUE THREAD

**Issue by SeeN1975** [VRGhost/PyPush#7]
Hello, I first apologize for my English. 
I have tried to install it but I have not had it. I enclose the steps that I followed.

`
sudo su

apt-get update

cd /

apt-get install python-pip

apt-get install git

apt-get install libglib2.0-dev libusb-dev libdbus-1-dev libudev-dev libical-dev libreadline-dev libboost-all-dev libbluetooth-dev ipython python-dev pybluez

wget https://github.com/VRGhost/PyPush/archive/master.zip

unzip ./master.zip

cd PyPush-master

pip install -r ./requirements/prod.txt

pip install -r ./requirements/bluez.txt

./bin/serve.sh --ble_driver pybluez --ble_device hci0 web_ui

`

Show me the following error:
`TypeError: Can't instantiate abstract class API with abstract methods createMicrobotFromUUID`

Thanks for your time

**Comment by Mak601** [comment]
For PyBluez
remove 
@abstractmethod
    def createMicrobotFromUUID(self, uuid):
from
PyPush/PyPush/lib/ble/iApi.py

**Comment by VRGhost** [comment]
Hi,

No, this abstract class is required for higher layers of software to function correctly.  This particular method is used to create microbot's bluetooth address is already known (stored in the database) when the server starts up.

I (or you) just have to implement `createMicrobotFromUUID` method in the pyBlueZ version of the stack. This should not be a problem as this method just creates new microbot instance connected to the device address provided.

**Comment by Mak601** [comment]
Hello,
I think I was in a hurry yesterday and didn't finish code analysis properly.
Suspect, its the reason, I am not able to pair with MicroBot.
I will try to write this method in pyBluez stack, but not very strong in Py.
Trying to create library for Android basing on your code.
Even with this source don't have clear picture how to authorise pairing.
Without createMicrobotFromUUID in stack, one device giving me - Unpairable device.
Second once I reached state when microbot begins blink and wait touch for pair, after that - device is busy, cannot write characteristic.

**Comment by VRGhost** [comment]
This should be resolved now thanks to @javaftper.
