### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by SeeN1975** [VRGhost/PyPush#8]
Hello, the docker is compiled to be executed on a raspberry pi?
If so, I can not do it right, I get the following message:

`standard_init_linux.go:178: exec user process caused "exec format error"`

**Comment by VRGhost** [comment]
Errr.

To be honest, I was not even aware that Docker is supported on Raspberry PI.

No, the docker image is for x86_64 cpus, not ARM ones. Shouldn't be too hard to port though.
